// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9d9egrPOP7xRClv16t40gOUYRq7kI9TM',
    appId: '1:965591455065:web:9d34f72c20363ddea96848',
    messagingSenderId: '965591455065',
    projectId: 'campusskillexchange-fbf8a',
    authDomain: 'campusskillexchange-fbf8a.firebaseapp.com',
    storageBucket: 'campusskillexchange-fbf8a.firebasestorage.app',
    measurementId: 'G-W6Y5KNLQ72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxtVh9O3I3n8h0jl4iGjFOlyu3TnBAfQo',
    appId: '1:965591455065:android:d5f29defb1f157e6a96848',
    messagingSenderId: '965591455065',
    projectId: 'campusskillexchange-fbf8a',
    storageBucket: 'campusskillexchange-fbf8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC8dsdUcVIk-mgTifRFmVu1MB8aDOoDS0',
    appId: '1:965591455065:ios:76bef767386df1f5a96848',
    messagingSenderId: '965591455065',
    projectId: 'campusskillexchange-fbf8a',
    storageBucket: 'campusskillexchange-fbf8a.firebasestorage.app',
    iosBundleId: 'com.example.campusskillexchangeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC8dsdUcVIk-mgTifRFmVu1MB8aDOoDS0',
    appId: '1:965591455065:ios:76bef767386df1f5a96848',
    messagingSenderId: '965591455065',
    projectId: 'campusskillexchange-fbf8a',
    storageBucket: 'campusskillexchange-fbf8a.firebasestorage.app',
    iosBundleId: 'com.example.campusskillexchangeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9d9egrPOP7xRClv16t40gOUYRq7kI9TM',
    appId: '1:965591455065:web:7b29a62a211de863a96848',
    messagingSenderId: '965591455065',
    projectId: 'campusskillexchange-fbf8a',
    authDomain: 'campusskillexchange-fbf8a.firebaseapp.com',
    storageBucket: 'campusskillexchange-fbf8a.firebasestorage.app',
    measurementId: 'G-6DL53G58ZW',
  );
}
