import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/service_request.dart';
import '../models/role.dart';
import '../services/firebase_service.dart';

class PostRequestScreen extends StatefulWidget {
  final ServiceRequest? requestToEdit;
  const PostRequestScreen({super.key, this.requestToEdit});

  @override
  State<PostRequestScreen> createState() => _PostRequestScreenState();
}

class _PostRequestScreenState extends State<PostRequestScreen> {
  final _formKey = GlobalKey<FormState>();
  bool _isLoading = false;
  
  String _title = '';
  String _description = '';
  String _category = 'Programming';
  double _budget = 0.0;
  DateTime _deadline = DateTime.now().add(const Duration(days: 7));

  @override
  void initState() {
    super.initState();
    _checkUserRole();
    if (widget.requestToEdit != null) {
      _title = widget.requestToEdit!.title;
      _description = widget.requestToEdit!.description;
      _category = widget.requestToEdit!.category;
      _budget = widget.requestToEdit!.budget;
      _deadline = widget.requestToEdit!.deadline;
    }
  }

  Future<void> _checkUserRole() async {
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      final doc = await FirebaseFirestore.instance.collection('users').doc(user.uid).get();
      final userData = doc.data() ?? {};
      final userRole = RoleHelper.fromString(userData['role']);
      
      // Students and Employers can post requests
      if (userRole != Role.student && userRole != Role.employer) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('UNAUTHORIZED: Only students and employers can post requests.'),
              backgroundColor: Colors.redAccent,
            ),
          );
          Navigator.pop(context);
        }
      }
    }
  }

  final List<String> _categories = [
    'Programming',
    'IT',
    'Design',
    'Multimedia',
    'Security',
    'Academic',
    'Other'
  ];

  Future<void> _selectDeadline() async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: _deadline,
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 365)),
      builder: (context, child) {
        return Theme(
          data: Theme.of(context).copyWith(
            colorScheme: ColorScheme.dark(
              primary: const Color(0xFFFF6B6B),
              onPrimary: Colors.white,
              surface: Theme.of(context).colorScheme.surface,
            ),
          ),
          child: child!,
        );
      },
    );
    if (picked != null && picked != _deadline) {
      setState(() => _deadline = picked);
    }
  }

  void _submit() async {
    if (!_formKey.currentState!.validate()) return;
    _formKey.currentState!.save();

    final user = FirebaseAuth.instance.currentUser;
    if (user == null) return;

    setState(() => _isLoading = true);

    try {
      final userDoc = await FirebaseFirestore.instance.collection('users').doc(user.uid).get();
      final userName = userDoc.data()?['name'] ?? 'User';

      if (widget.requestToEdit != null) {
        await FirebaseService().updateServiceRequest(widget.requestToEdit!.id, {
          'title': _title,
          'description': _description,
          'category': _category,
          'budget': _budget,
          'deadline': Timestamp.fromDate(_deadline),
        });
      } else {
        final request = ServiceRequest(
          id: '', // Generated by Firestore
          title: _title,
          description: _description,
          category: _category,
          requesterId: user.uid,
          requesterName: userName,
          budget: _budget,
          deadline: _deadline,
          createdAt: DateTime.now(),
        );

        await FirebaseService().postServiceRequest(request.toMap());
      }

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Request posted successfully!'), backgroundColor: Colors.green),
        );
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e'), backgroundColor: Colors.red),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Post Service Request'),
      ),
      body: SingleChildScrollView(
        padding: EdgeInsets.all(24),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Text(
                'What do you need help with?',
                style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: Colors.white),
              ),
              SizedBox(height: 8),
              Text(
                'Describe your request and set a budget.',
                style: TextStyle(color: Theme.of(context).textTheme.bodyMedium!.color!.withValues(alpha: 0.7)),
              ),
              SizedBox(height: 32),
              _buildTextField(
                label: 'Title',
                hint: 'e.g., Help with Flutter Animation',
                onSaved: (v) => _title = v!,
                validator: (v) => v!.isEmpty ? 'Please enter a title' : null,
              ),
              SizedBox(height: 16),
              _buildTextField(
                label: 'Description',
                hint: 'Provide details about the task...',
                maxLines: 4,
                onSaved: (v) => _description = v!,
                validator: (v) => v!.isEmpty ? 'Please enter a description' : null,
              ),
              SizedBox(height: 16),
              DropdownButtonFormField<String>(
                initialValue: _category,
                dropdownColor: Theme.of(context).colorScheme.surface,
                decoration: _inputDecoration('Category'),
                items: _categories.map((c) => DropdownMenuItem(value: c, child: Text(c))).toList(),
                onChanged: (v) => setState(() => _category = v!),
              ),
              SizedBox(height: 16),
              _buildTextField(
                label: 'Budget (UGX)',
                hint: '50000',
                keyboardType: TextInputType.number,
                onSaved: (v) => _budget = double.tryParse(v!) ?? 0.0,
                validator: (v) {
                  final val = double.tryParse(v ?? '');
                  if (val == null) return 'Enter a valid number';
                  if (val < 0) return 'Budget cannot be negative';
                  return null;
                },
              ),
              SizedBox(height: 16),
              InkWell(
                onTap: _selectDeadline,
                child: InputDecorator(
                  decoration: _inputDecoration('Deadline'),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(
                        '${_deadline.year}-${_deadline.month}-${_deadline.day}',
                        style: TextStyle(color: Colors.white),
                      ),
                      Icon(Icons.calendar_today, color: Color(0xFFFF6B6B)),
                    ],
                  ),
                ),
              ),
              SizedBox(height: 48),
              if (_isLoading)
                Center(child: CircularProgressIndicator(color: Color(0xFFFF6B6B)))
              else
                ElevatedButton(
                  onPressed: _submit,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFFFF6B6B),
                    foregroundColor: Colors.white,
                    padding: EdgeInsets.symmetric(vertical: 16),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  ),
                  child: Text('Post Request', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
                ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildTextField({
    required String label,
    required String hint,
    int maxLines = 1,
    TextInputType keyboardType = TextInputType.text,
    required FormFieldSetter<String> onSaved,
    required FormFieldValidator<String> validator,
  }) {
    return TextFormField(
      style: TextStyle(color: Colors.white),
      decoration: _inputDecoration(label).copyWith(hintText: hint, hintStyle: TextStyle(color: Colors.white24)),
      maxLines: maxLines,
      initialValue: label.contains('Budget') ? _budget.toString() : (label == 'Title' ? _title : (label == 'Description' ? _description : null)),
      onSaved: onSaved,
      validator: validator,
    );
  }

  InputDecoration _inputDecoration(String label) {
    return InputDecoration(
      labelText: label,
      labelStyle: TextStyle(color: Color(0xFFFF6B6B)),
      filled: true,
      fillColor: Theme.of(context).colorScheme.surface,
      border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none),
      enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none),
      focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: const BorderSide(color: Color(0xFFFF6B6B))),
    );
  }
}
